name: ogurets
version: 4.0.2
description: Gherkin/Cucumber implementation in dart, supporting classes and simple libraries, hooks, dependency injection, and all the things you would want in an easy to use format.
homepage: https://github.com/dart-ogurets/Ogurets
dependencies:
  logging: ^1.0.0
  args: ^2.0.0
  ansicolor: ^2.0.1
  intl: ^0.17.0
  sprintf: ^6.0.0
  collection: ^1.15.0
environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.14.4
